create table service(
	id INT primary key identity,
	nom VARCHAR(50) NOT NULL UNIQUE,
	taux  DECIMAL(10,2)
);
drop table service
SET IDENTITY_INSERT service ON;

select * from service where taux > 200;

insert into service (id, nom, taux ) values (1, 'Iguana iguana', '276.58');
insert into service (id, nom, taux ) values (2, 'Corvus albicollis', '257.54');
insert into service (id, nom, taux ) values (3, 'Chordeiles minor', '173.33');
insert into service (id, nom, taux ) values (4, 'Felis rufus', '236.69');
insert into service (id, nom, taux ) values (5, 'Phalacrocorax niger', '64.50');
insert into service (id, nom, taux ) values (6, 'Macaca radiata', '59.73');
insert into service (id, nom, taux ) values (7, 'Anser caerulescens', '233.27');
insert into service (id, nom, taux ) values (8, 'Ardea cinerea', '276.24');
insert into service (id, nom, taux ) values (9, 'Dendrocitta vagabunda', '178.09');
insert into service (id, nom, taux ) values (10, 'Castor canadensis', '169.46');
insert into service (id, nom, taux ) values (11, 'Larus fuliginosus', '79.89');
insert into service (id, nom, taux ) values (12, 'Fulica cristata', '285.73');
insert into service (id, nom, taux ) values (13, 'Cynictis penicillata', '266.00');
insert into service (id, nom, taux ) values (14, 'Axis axis', '76.74');
insert into service (id, nom, taux ) values (15, 'Dicrostonyx groenlandicus', '65.14');
insert into service (id, nom, taux ) values (16, 'Equus burchelli', '115.73');
insert into service (id, nom, taux ) values (17, 'Branta canadensis', '244.13');
insert into service (id, nom, taux ) values (18, 'Aegypius occipitalis', '224.95');
insert into service (id, nom, taux ) values (19, 'Acrobates pygmaeus', '139.88');
insert into service (id, nom, taux ) values (20, 'Leptoptilus dubius', '261.19');
insert into service (id, nom, taux ) values (21, 'Castor fiber', '286.32');
insert into service (id, nom, taux ) values (22, 'Coluber constrictor', '141.93');
insert into service (id, nom, taux ) values (23, 'Alectura lathami', '278.63');
insert into service (id, nom, taux ) values (24, 'Crotaphytus collaris', '198.14');
insert into service (id, nom, taux ) values (25, 'Smithopsis crassicaudata', '63.23');
insert into service (id, nom, taux ) values (26, 'Microcebus murinus', '283.25');
insert into service (id, nom, taux ) values (27, 'Threskionis aethiopicus', '155.77');
insert into service (id, nom, taux ) values (28, 'Grus rubicundus', '271.64');
insert into service (id, nom, taux ) values (29, 'Geospiza sp.', '266.66');
insert into service (id, nom, taux ) values (30, 'Merops nubicus', '192.67');
insert into service (id, nom, taux ) values (31, 'Nesomimus trifasciatus', '185.75');
insert into service (id, nom, taux ) values (32, 'Chelodina longicollis', '244.52');
insert into service (id, nom, taux ) values (33, 'Canis lupus lycaon', '73.49');
insert into service (id, nom, taux ) values (34, 'Grus rubicundus', '198.43');
insert into service (id, nom, taux ) values (35, 'Ninox superciliaris', '294.02');
insert into service (id, nom, taux ) values (36, 'Uraeginthus granatina', '62.48');
insert into service (id, nom, taux ) values (37, 'Panthera pardus', '94.21');
insert into service (id, nom, taux ) values (38, 'Diceros bicornis', '188.81');
insert into service (id, nom, taux ) values (39, 'Pteronura brasiliensis', '138.94');
insert into service (id, nom, taux ) values (40, 'Callorhinus ursinus', '147.56');
insert into service (id, nom, taux ) values (41, 'Coracias caudata', '192.01');
insert into service (id, nom, taux ) values (42, 'Macropus fuliginosus', '260.82');
insert into service (id, nom, taux ) values (43, 'Equus hemionus', '84.52');
insert into service (id, nom, taux ) values (44, 'Neophoca cinerea', '69.55');
insert into service (id, nom, taux ) values (45, 'Procyon lotor', '276.91');
insert into service (id, nom, taux ) values (46, 'Microcebus murinus', '297.96');
insert into service (id, nom, taux ) values (47, 'Ninox superciliaris', '119.01');
insert into service (id, nom, taux ) values (48, 'Ceratotherium simum', '229.38');
insert into service (id, nom, taux ) values (49, 'Lepus townsendii', '233.36');
insert into service (id, nom, taux ) values (50, 'Connochaetus taurinus', '108.70');
insert into service (id, nom, taux ) values (51, 'Trichoglossus haematodus moluccanus', '237.62');
insert into service (id, nom, taux ) values (52, 'Eira barbata', '93.35');
insert into service (id, nom, taux ) values (53, 'Elephas maximus bengalensis', '184.26');
insert into service (id, nom, taux ) values (54, 'Vicugna vicugna', '290.22');
insert into service (id, nom, taux ) values (55, 'Ovis dalli stonei', '170.57');
insert into service (id, nom, taux ) values (56, 'Actophilornis africanus', '110.88');
insert into service (id, nom, taux ) values (57, 'Cochlearius cochlearius', '171.03');
insert into service (id, nom, taux ) values (58, 'Alcelaphus buselaphus caama', '279.87');
insert into service (id, nom, taux ) values (59, 'Giraffe camelopardalis', '64.50');
insert into service (id, nom, taux ) values (60, 'Bradypus tridactylus', '218.81');
insert into service (id, nom, taux ) values (61, 'Trichosurus vulpecula', '134.50');
insert into service (id, nom, taux ) values (62, 'Orcinus orca', '298.92');
insert into service (id, nom, taux ) values (63, 'Streptopelia decipiens', '165.77');
insert into service (id, nom, taux ) values (64, 'Kobus leche robertsi', '98.62');
insert into service (id, nom, taux ) values (65, 'Lama pacos', '227.66');
insert into service (id, nom, taux ) values (66, 'Oryx gazella', '164.40');
insert into service (id, nom, taux ) values (67, 'Bos taurus', '116.71');
insert into service (id, nom, taux ) values (68, 'Macaca mulatta', '290.40');
insert into service (id, nom, taux ) values (69, 'Varanus sp.', '201.66');
insert into service (id, nom, taux ) values (70, 'Ursus americanus', '168.52');
insert into service (id, nom, taux ) values (71, 'Rana sp.', '261.76');
insert into service (id, nom, taux ) values (72, 'Dasyurus maculatus', '94.72');
insert into service (id, nom, taux ) values (73, 'Bubalus arnee', '102.72');
insert into service (id, nom, taux ) values (74, 'Pycnonotus nigricans', '159.71');
insert into service (id, nom, taux ) values (75, 'Kobus defassa', '219.72');
insert into service (id, nom, taux ) values (76, 'Graspus graspus', '171.91');
insert into service (id, nom, taux ) values (77, 'Cervus duvauceli', '291.53');
insert into service (id, nom, taux ) values (78, 'Naja sp.', '197.42');
insert into service (id, nom, taux ) values (79, 'Hystrix indica', '138.78');
insert into service (id, nom, taux ) values (80, 'Phalacrocorax varius', '114.23');
insert into service (id, nom, taux ) values (81, 'Priodontes maximus', '72.79');
insert into service (id, nom, taux ) values (82, 'Ardea golieth', '272.15');
insert into service (id, nom, taux ) values (83, 'Taxidea taxus', '81.67');
insert into service (id, nom, taux ) values (84, 'Antechinus flavipes', '180.93');
insert into service (id, nom, taux ) values (85, 'Odocoilenaus virginianus', '248.78');
insert into service (id, nom, taux ) values (86, 'Varanus komodensis', '126.60');
insert into service (id, nom, taux ) values (87, 'Bucephala clangula', '167.01');
insert into service (id, nom, taux ) values (88, 'Canis lupus', '285.33');
insert into service (id, nom, taux ) values (89, 'Neophoca cinerea', '58.02');
insert into service (id, nom, taux ) values (90, 'Macropus robustus', '130.79');
insert into service (id, nom, taux ) values (91, 'Spilogale gracilis', '282.02');
insert into service (id, nom, taux ) values (92, 'Dasyurus viverrinus', '229.01');
insert into service (id, nom, taux ) values (93, 'Nasua narica', '270.42');
insert into service (id, nom, taux ) values (94, 'Mirounga leonina', '163.16');
insert into service (id, nom, taux ) values (95, 'Grus rubicundus', '80.69');
insert into service (id, nom, taux ) values (96, 'Coluber constrictor', '236.63');
insert into service (id, nom, taux ) values (97, 'Macropus rufus', '190.71');
insert into service (id, nom, taux ) values (98, 'Cebus albifrons', '76.33');
insert into service (id, nom, taux ) values (99, 'Casmerodius albus', '207.53');
insert into service (id, nom, taux ) values (100, 'Genetta genetta', '72.68');

