create database concessionnaire
use concessionnaire

create table Vendeur (
	id INT primary key identity,
	nom VARCHAR(50) NOT NULL,
	telephone VARCHAR(50),
	email VARCHAR(50),
	adresse VARCHAR(50),
	ville VARCHAR(50),
	province VARCHAR(50)
);

SET IDENTITY_INSERT Vendeur ON

insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (1, 'Daugherty Group', '561-354-9797', 'nfried0@myspace.com', '1968 Southridge Hill', 'Boynton Beach', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (2, 'Bashirian, Hartmann and Runte', '202-193-8059', 'mchristoffe1@people.com.cn', '57 Badeau Way', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (3, 'Crooks-Botsford', '941-894-4333', 'cbelison2@opensource.org', '2531 Shelley Center', 'Sarasota', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (4, 'Hand and Sons', '330-142-6362', 'tspriggs3@pen.io', '22351 Oriole Plaza', 'Youngstown', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (5, 'Kub LLC', '518-241-2640', 'wilyas4@skyrock.com', '000 Westridge Alley', 'Albany', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (6, 'Padberg, Collier and Becker', '415-998-1358', 'atomasek5@nytimes.com', '99 Bellgrove Drive', 'San Francisco', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (7, 'Howell, Kutch and Littel', '626-468-3029', 'ecosens6@jugem.jp', '92 Kennedy Street', 'Pasadena', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (8, 'Volkman-Toy', '941-415-5323', 'lverryan7@cam.ac.uk', '7 Carberry Center', 'Seminole', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (9, 'Conroy-Rath', '303-334-2585', 'lcampey8@dion.ne.jp', '1 Grayhawk Hill', 'Denver', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (10, 'O''Keefe LLC', '215-219-0038', 'tdevons9@goo.gl', '13831 Carioca Hill', 'Philadelphia', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (11, 'West-Hilpert', '301-561-1284', 'cjamiesona@discovery.com', '9 Toban Parkway', 'Hyattsville', 'Maryland');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (12, 'Dietrich LLC', '913-777-3679', 'sdehoogeb@networksolutions.com', '775 Russell Hill', 'Kansas City', 'Kansas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (13, 'Herman and Sons', '719-355-9788', 'mrotheryc@wufoo.com', '86235 Twin Pines Avenue', 'Colorado Springs', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (14, 'Zemlak, Kshlerin and Bogisich', '832-967-5554', 'ladnamd@1688.com', '8 Emmet Circle', 'Houston', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (15, 'Hahn, Bode and Nicolas', '414-144-0071', 'thumfreye@cdbaby.com', '83731 Schlimgen Circle', 'Milwaukee', 'Wisconsin');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (16, 'Schneider-Gulgowski', '314-479-3928', 'kfurmengerf@dmoz.org', '34 Village Parkway', 'Saint Louis', 'Missouri');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (17, 'Zemlak, Schamberger and Kemmer', '312-544-8667', 'lmcconwayg@technorati.com', '9 Sommers Crossing', 'Chicago', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (18, 'Raynor-Simonis', '651-415-7495', 'sjewetth@buzzfeed.com', '2 Porter Terrace', 'Minneapolis', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (19, 'Heathcote-Auer', '202-181-0199', 'rcodii@statcounter.com', '19 Northview Hill', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (20, 'Hilpert-Lubowitz', '646-273-2006', 'truppertzj@netlog.com', '0 Stoughton Drive', 'New York City', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (21, 'Hyatt-Stiedemann', '903-488-1319', 'rrigatek@pen.io', '9 Lakewood Gardens Crossing', 'Texarkana', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (22, 'Leuschke-Simonis', '951-635-4818', 'kdudnyl@cbslocal.com', '12871 Talisman Alley', 'Corona', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (23, 'Runte, Volkman and Haag', '818-770-1167', 'fkilduffm@reddit.com', '59 Kingsford Terrace', 'Los Angeles', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (24, 'Marvin and Sons', '615-467-8469', 'dcloutern@miibeian.gov.cn', '64 Armistice Court', 'Murfreesboro', 'Tennessee');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (25, 'Hegmann LLC', '206-578-4483', 'nlakelando@vinaora.com', '302 Hoard Crossing', 'Seattle', 'Washington');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (26, 'Bogisich, Cronin and Powlowski', '404-606-4757', 'awollenp@bloomberg.com', '439 Maple Court', 'Lawrenceville', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (27, 'Roob and Sons', '860-157-3858', 'gspellsworthq@google.co.uk', '5218 Morning Avenue', 'Hartford', 'Connecticut');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (28, 'Dibbert, Medhurst and Bernhard', '317-131-4113', 'nhaysarr@blogs.com', '31279 Sheridan Drive', 'Indianapolis', 'Indiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (29, 'Stokes-Carter', '979-669-0918', 'dpols@dot.gov', '28 Lawn Park', 'Bryan', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (30, 'Weissnat-Hegmann', '419-348-3280', 'balwent@1und1.de', '4287 Mariners Cove Court', 'Toledo', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (31, 'Fritsch, Aufderhar and Hane', '818-355-4439', 'hkupisu@indiatimes.com', '31 Dryden Point', 'Torrance', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (32, 'Halvorson-Wyman', '615-299-4768', 'tsyddallv@example.com', '2106 Kinsman Trail', 'Nashville', 'Tennessee');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (33, 'Schinner, Morar and Sauer', '765-371-5677', 'eeasbiew@bluehost.com', '885 Mcbride Park', 'Crawfordsville', 'Indiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (34, 'Doyle, Hintz and Haley', '814-693-1220', 'jdartex@wikispaces.com', '80816 Mariners Cove Park', 'Erie', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (35, 'Wuckert, Hills and Skiles', '254-294-9308', 'aitzhaieky@hhs.gov', '601 Harper Way', 'Waco', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (36, 'Considine and Sons', '314-638-2819', 'mconnahz@army.mil', '00 Marquette Place', 'Saint Louis', 'Missouri');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (37, 'Blick LLC', '502-447-2641', 'cperllman10@usda.gov', '92 Blue Bill Park Junction', 'Louisville', 'Kentucky');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (38, 'O''Kon and Sons', '970-889-6694', 'jblincko11@google.nl', '312 Fordem Trail', 'Greeley', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (39, 'Sipes Inc', '617-241-4654', 'lcurrington12@microsoft.com', '9 Lakewood Trail', 'Boston', 'Massachusetts');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (40, 'Morissette, Satterfield and Goyette', '661-675-9132', 'rmcramsey13@alexa.com', '88224 Superior Lane', 'Bakersfield', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (41, 'Kassulke Inc', '404-441-8504', 'cbrosius14@4shared.com', '2598 Lotheville Junction', 'Atlanta', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (42, 'Becker Inc', '806-104-9940', 'lriddick15@techcrunch.com', '5565 Elka Terrace', 'Amarillo', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (43, 'Donnelly and Sons', '816-950-9780', 'afeaster16@ameblo.jp', '2 Talmadge Park', 'Kansas City', 'Kansas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (44, 'Graham-Ebert', '505-582-3593', 'vmcadam17@tuttocitta.it', '843 Forest Parkway', 'Albuquerque', 'New Mexico');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (45, 'Kub-Stark', '312-948-0767', 'taprahamian18@sina.com.cn', '73 Debs Center', 'Chicago', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (46, 'Hilll and Sons', '573-756-4096', 'sondrus19@jimdo.com', '637 Gina Terrace', 'Columbia', 'Missouri');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (47, 'Corwin Inc', '240-846-0649', 'fbrodhead1a@noaa.gov', '1 Park Meadow Way', 'Silver Spring', 'Maryland');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (48, 'Gulgowski-Casper', '602-804-4076', 'sstenton1b@blogspot.com', '8 6th Terrace', 'Phoenix', 'Arizona');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (49, 'Roberts Inc', '518-549-8803', 'aspira1c@thetimes.co.uk', '3 5th Alley', 'Albany', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (50, 'Hodkiewicz-Rowe', '202-954-2194', 'teastment1d@bizjournals.com', '7122 International Way', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (51, 'Bartoletti LLC', '650-243-1704', 'vmenghi1e@sciencedirect.com', '0 Stang Circle', 'Los Angeles', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (52, 'Keeling-Frami', '707-829-5665', 'mgerding1f@dmoz.org', '7676 Grover Pass', 'Santa Rosa', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (53, 'Beer, Bosco and Jacobson', '816-664-8882', 'imisken1g@storify.com', '26866 Kenwood Hill', 'Kansas City', 'Missouri');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (54, 'Leannon, Wintheiser and Lubowitz', '405-338-5228', 'mbarriball1h@mozilla.com', '9 Shoshone Court', 'Oklahoma City', 'Oklahoma');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (55, 'Hyatt-Kohler', '513-320-5956', 'cbirkenshaw1i@bbb.org', '607 Ilene Pass', 'Cincinnati', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (56, 'White Group', '850-379-7929', 'amardell1j@jigsy.com', '9950 Old Gate Crossing', 'Tallahassee', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (57, 'Keebler Group', '207-404-1524', 'scrady1k@wordpress.com', '01 Alpine Pass', 'Portland', 'Maine');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (58, 'Leannon-Lang', '702-326-8826', 'hparton1l@bbb.org', '2 Anniversary Crossing', 'Las Vegas', 'Nevada');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (59, 'Heathcote and Sons', '901-990-1374', 'cmcgaughay1m@altervista.org', '06 Norway Maple Circle', 'Memphis', 'Tennessee');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (60, 'Gorczany-Abernathy', '254-663-6650', 'rbiddulph1n@g.co', '69079 Everett Hill', 'Temple', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (61, 'Gaylord and Sons', '304-808-9533', 'gsharply1o@360.cn', '32 Glacier Hill Road', 'Huntington', 'West Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (62, 'Bins, Rodriguez and Crist', '302-480-1442', 'hbarkas1p@telegraph.co.uk', '24 Heffernan Junction', 'Wilmington', 'Delaware');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (63, 'Brown Inc', '501-318-4184', 'abims1q@ovh.net', '06 Union Pass', 'Little Rock', 'Arkansas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (64, 'Reichel, Gleason and Smitham', '205-691-1330', 'jellif1r@amazon.co.uk', '0 Dakota Park', 'Birmingham', 'Alabama');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (65, 'Abshire, Wolf and Nikolaus', '256-632-4555', 'tgarforth1s@wiley.com', '18374 Mallard Park', 'Huntsville', 'Alabama');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (66, 'Osinski LLC', '520-766-0825', 'nserrels1t@indiatimes.com', '8 Dryden Crossing', 'Tucson', 'Arizona');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (67, 'Rau Inc', '904-708-0941', 'cbenedicte1u@webmd.com', '962 Stephen Street', 'Jacksonville', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (68, 'Glover-Ondricka', '404-639-6161', 'hriach1v@usa.gov', '7 John Wall Avenue', 'Atlanta', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (69, 'Sanford, Herman and Weimann', '773-268-5182', 'rmarkos1w@bizjournals.com', '37346 Hanover Parkway', 'Chicago', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (70, 'Ritchie LLC', '646-122-9434', 'jhekkert1x@theatlantic.com', '23544 Ridgeway Pass', 'Brooklyn', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (71, 'Lockman-Mante', '775-146-0531', 'cgarstang1y@globo.com', '541 Sheridan Pass', 'Carson City', 'Nevada');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (72, 'Murray Group', '561-501-2761', 'ttorrisi1z@eventbrite.com', '7859 Walton Way', 'West Palm Beach', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (73, 'Davis and Sons', '203-376-2215', 'achat20@oracle.com', '73 Division Hill', 'Waterbury', 'Connecticut');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (74, 'Orn Inc', '318-230-9163', 'lrenad21@google.nl', '25284 Del Sol Parkway', 'Monroe', 'Louisiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (75, 'Gutkowski Inc', '314-691-7987', 'wivshin22@fda.gov', '1 Corscot Parkway', 'Saint Louis', 'Missouri');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (76, 'Klocko Inc', '212-646-8279', 'pbadsey23@zimbio.com', '95142 Northview Alley', 'New York City', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (77, 'Schuppe-Tremblay', '212-102-3345', 'otee24@smh.com.au', '493 Schmedeman Court', 'New York City', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (78, 'Lebsack, Gulgowski and Moen', '818-912-8605', 'gnaisey25@nationalgeographic.com', '02 Dahle Trail', 'Glendale', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (79, 'Crist, Mills and Cartwright', '515-272-1111', 'mwhitchurch26@quantcast.com', '392 Clove Street', 'Des Moines', 'Iowa');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (80, 'Morar, Roberts and Nikolaus', '515-841-1288', 'stissell27@hp.com', '3 Schlimgen Trail', 'Des Moines', 'Iowa');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (81, 'Reichert-MacGyver', '214-709-5051', 'hoppery28@istockphoto.com', '6 Victoria Pass', 'Dallas', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (82, 'Weimann, Russel and Jaskolski', '801-787-1780', 'cgreatland29@wikispaces.com', '2786 Drewry Pass', 'Salt Lake City', 'Utah');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (83, 'Raynor-Bartoletti', '415-499-0375', 'vharvett2a@mtv.com', '34 Redwing Lane', 'San Francisco', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (84, 'Stehr, Moore and Dicki', '215-500-0004', 'bagass2b@linkedin.com', '29808 Weeping Birch Court', 'Philadelphia', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (85, 'Turner Inc', '860-584-6352', 'cohoey2c@amazon.com', '177 Paget Way', 'Hartford', 'Connecticut');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (86, 'Kessler Inc', '281-886-8513', 'agummary2d@themeforest.net', '7 Thackeray Point', 'Houston', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (87, 'Conroy-Toy', '443-653-4355', 'cgrinvalds2e@cpanel.net', '926 Jay Road', 'Annapolis', 'Maryland');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (88, 'O''Keefe-Roberts', '925-146-1737', 'shighman2f@deviantart.com', '31 Maple Wood Point', 'Concord', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (89, 'Torp Inc', '323-985-1907', 'rbinding2g@java.com', '34 Dennis Terrace', 'Burbank', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (90, 'Pagac-Macejkovic', '646-926-9547', 'nchawkley2h@google.com.hk', '015 Bonner Road', 'New York City', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (91, 'Muller-Pfannerstill', '508-628-3795', 'sgordge2i@nbcnews.com', '31 Stuart Point', 'Waltham', 'Massachusetts');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (92, 'Shields-Rosenbaum', '605-785-3382', 'epetras2j@usgs.gov', '76996 Homewood Crossing', 'Sioux Falls', 'South Dakota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (93, 'Rogahn, Ernser and Stark', '318-728-6945', 'vjaggli2k@yahoo.com', '9316 Corscot Junction', 'Shreveport', 'Louisiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (94, 'Fay Inc', '503-777-6943', 'kmaryet2l@reuters.com', '4312 Rockefeller Road', 'Portland', 'Oregon');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (95, 'Hintz, Kuvalis and Beatty', '904-418-1930', 'lpaddon2m@marriott.com', '88 Kim Plaza', 'Jacksonville', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (96, 'Gulgowski-Mosciski', '515-752-7034', 'kgallagher2n@epa.gov', '03934 Clyde Gallagher Trail', 'Des Moines', 'Iowa');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (97, 'Gottlieb Inc', '303-581-1941', 'bmccrorie2o@webeden.co.uk', '07583 Upham Point', 'Arvada', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (98, 'Hegmann, Stokes and Watsica', '415-692-1768', 'ghandsheart2p@seesaa.net', '155 Surrey Parkway', 'San Francisco', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (99, 'Hintz, Hane and Romaguera', '619-388-7892', 'ntiebe2q@nbcnews.com', '798 Steensland Point', 'San Diego', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (100, 'Fritsch and Sons', '850-696-6442', 'gwicklen2r@ca.gov', '6960 Nelson Crossing', 'Pensacola', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (101, 'Dare, Kulas and Koch', '309-977-5377', 'mbottleson2s@theglobeandmail.com', '7817 Bowman Place', 'Peoria', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (102, 'Hahn-Upton', '267-635-6732', 'jhaggett2t@timesonline.co.uk', '91 Derek Avenue', 'Levittown', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (103, 'Dooley and Sons', '202-232-7293', 'ypidcock2u@state.tx.us', '76 Talmadge Drive', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (104, 'Reichert-Rau', '202-822-8032', 'abalser2v@oracle.com', '114 Talmadge Alley', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (105, 'Hayes, Moore and Feil', '210-648-6562', 'hgoodisson2w@umn.edu', '2 Rigney Crossing', 'San Antonio', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (106, 'Hettinger and Sons', '716-140-5018', 'kbubb2x@mozilla.com', '835 Carioca Street', 'Buffalo', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (107, 'Hirthe-Robel', '806-830-8234', 'boultram2y@indiatimes.com', '1133 Saint Paul Junction', 'Lubbock', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (108, 'Schneider Group', '910-784-9434', 'mpluck2z@biblegateway.com', '27 Jackson Pass', 'Wilmington', 'North Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (109, 'Corkery, Leannon and Mohr', '678-819-7818', 'tsotheby30@reddit.com', '2693 Northridge Avenue', 'Gainesville', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (110, 'Schulist-Stamm', '601-894-0310', 'kraynham31@gizmodo.com', '4 Victoria Street', 'Meridian', 'Mississippi');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (111, 'Leffler-Lind', '202-210-9288', 'gcalverley32@vimeo.com', '9 Artisan Lane', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (112, 'Blick, Moen and Bashirian', '714-508-6369', 'jorkney33@purevolume.com', '4 Susan Trail', 'Garden Grove', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (113, 'Jenkins, Miller and Hegmann', '512-549-6549', 'btewkesberrie34@networksolutions.com', '115 Kingsford Park', 'Austin', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (114, 'Veum, Deckow and Hayes', '202-336-2406', 'glainge35@alibaba.com', '57792 Nancy Terrace', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (115, 'Runolfsson, Carter and Botsford', '818-873-1506', 'jcurryer36@yelp.com', '4843 Dahle Place', 'Los Angeles', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (116, 'Hilpert, Kuhlman and Tillman', '214-198-5633', 'arocco37@nbcnews.com', '41413 Holy Cross Lane', 'Dallas', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (117, 'Hermann-Zieme', '413-727-3943', 'tbunner38@sfgate.com', '09681 Magdeline Way', 'Springfield', 'Massachusetts');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (118, 'Padberg Group', '504-338-8829', 'hburwood39@patch.com', '59720 Utah Place', 'New Orleans', 'Louisiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (119, 'Grant, McDermott and Berge', '850-463-7759', 'xblackaby3a@stanford.edu', '3105 Petterle Hill', 'Panama City', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (120, 'Krajcik-Stamm', '952-100-2797', 'kedlestone3b@aboutads.info', '14518 Cody Plaza', 'Young America', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (121, 'Leuschke-Kub', '619-220-5125', 'sgoodbar3c@telegraph.co.uk', '71245 Lake View Park', 'Chula Vista', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (122, 'Walker, Gleichner and Erdman', '615-889-6393', 'jfines3d@digg.com', '172 Kedzie Way', 'Nashville', 'Tennessee');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (123, 'Morar-Bogisich', '218-862-5216', 'amacaloren3e@ning.com', '40568 Hanover Circle', 'Duluth', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (124, 'Pollich Group', '206-482-4442', 'jbolte3f@fc2.com', '3 Bonner Parkway', 'Seattle', 'Washington');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (125, 'Streich-Casper', '413-304-8408', 'apococke3g@europa.eu', '08629 Butterfield Junction', 'Springfield', 'Massachusetts');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (126, 'Ledner Inc', '843-587-4169', 'ffahy3h@exblog.jp', '41 Hanson Point', 'Florence', 'South Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (127, 'Denesik-Osinski', '571-468-0083', 'rsellwood3i@ehow.com', '70 Parkside Terrace', 'Springfield', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (128, 'Braun and Sons', '407-383-9719', 'stwitchings3j@google.es', '895 Anhalt Circle', 'Winter Haven', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (129, 'Gaylord-Kuhlman', '862-228-4465', 'wliell3k@flavors.me', '3016 Comanche Street', 'Paterson', 'New Jersey');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (130, 'Rolfson, Cummings and Krajcik', '214-503-4818', 'wgeorge3l@fastcompany.com', '344 Orin Pass', 'Dallas', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (131, 'Satterfield and Sons', '619-450-7558', 'tmcclure3m@cisco.com', '76631 Larry Junction', 'San Diego', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (132, 'Huels, Kovacek and Romaguera', '540-415-9451', 'edeble3n@paypal.com', '2306 Dixon Junction', 'Roanoke', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (133, 'Cormier-Heaney', '540-291-0797', 'dpeckitt3o@nationalgeographic.com', '3 Towne Place', 'Roanoke', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (134, 'Green-Smitham', '770-371-5118', 'itowson3p@geocities.com', '3 Moose Avenue', 'Atlanta', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (135, 'Feest-Rolfson', '678-346-7825', 'cbeards3q@forbes.com', '67 Duke Hill', 'Alpharetta', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (136, 'Pouros, Spencer and Jacobi', '626-270-7946', 'ggamet3r@kickstarter.com', '1532 Sunfield Road', 'Burbank', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (137, 'Carroll-Hilll', '303-849-9296', 'ckondrachenko3s@utexas.edu', '3806 Express Alley', 'Denver', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (138, 'Kohler, Heller and Harris', '262-227-0119', 'hhonsch3t@blogger.com', '4 Pond Parkway', 'Milwaukee', 'Wisconsin');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (139, 'Kris-Mitchell', '623-714-3757', 'mvsanelli3u@etsy.com', '7713 Calypso Street', 'Phoenix', 'Arizona');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (140, 'Lynch, Hirthe and Legros', '415-703-2439', 'rfomichkin3v@unblog.fr', '91743 Marcy Trail', 'San Francisco', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (141, 'Wilkinson-Hartmann', '517-466-2989', 'bgravener3w@bandcamp.com', '172 Morningstar Alley', 'Lansing', 'Michigan');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (142, 'Lueilwitz-Heaney', '304-872-3246', 'mloweth3x@usgs.gov', '6 Veith Park', 'Charleston', 'West Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (143, 'Wilkinson Group', '404-994-7847', 'glapham3y@mashable.com', '1 Debra Park', 'Atlanta', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (144, 'Gibson-Lakin', '305-566-8740', 'kshermore3z@webnode.com', '57338 Comanche Way', 'Naples', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (145, 'Reilly, Sanford and Kris', '334-873-1453', 'aarrandale40@wikimedia.org', '60 Straubel Center', 'Montgomery', 'Alabama');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (146, 'Schoen, Weber and Stanton', '901-838-2834', 'fgoodright41@amazon.co.uk', '594 Novick Parkway', 'Memphis', 'Tennessee');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (147, 'Runte-Jakubowski', '228-729-8817', 'mmarle42@cisco.com', '22435 Sunnyside Park', 'Gulfport', 'Mississippi');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (148, 'Parker-Baumbach', '864-923-8822', 'mromanetti43@businesswire.com', '9978 2nd Center', 'Greenville', 'South Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (149, 'Thiel LLC', '832-907-9390', 'jgeram44@sfgate.com', '46601 Troy Trail', 'Houston', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (150, 'Bahringer-McGlynn', '651-375-3560', 'bbikker45@t.co', '635 Dunning Trail', 'Saint Paul', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (151, 'Jacobi Inc', '860-240-9350', 'tkamen46@freewebs.com', '470 Lake View Trail', 'Hartford', 'Connecticut');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (152, 'Grady, Jast and Kling', '406-101-3107', 'ealden47@parallels.com', '33 Paget Junction', 'Billings', 'Montana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (153, 'Schmeler and Sons', '602-189-7162', 'jmews48@skype.com', '3 Fallview Alley', 'Phoenix', 'Arizona');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (154, 'Maggio, Veum and Bruen', '309-473-2839', 'tchittie49@slashdot.org', '95585 Crownhardt Parkway', 'Peoria', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (155, 'Hoppe, Zemlak and Stokes', '214-189-0302', 'bclemas4a@pbs.org', '2 Starling Road', 'Dallas', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (156, 'Olson Group', '774-574-5545', 'aeburne4b@cocolog-nifty.com', '450 Paget Avenue', 'Worcester', 'Massachusetts');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (157, 'Quigley, Kutch and Oberbrunner', '727-957-2562', 'oashwood4c@yahoo.com', '68954 Toban Lane', 'Saint Petersburg', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (158, 'Skiles Inc', '570-640-1142', 'ygleeton4d@upenn.edu', '37 Mayfield Lane', 'Wilkes Barre', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (159, 'Legros Group', '818-663-6629', 'etriplow4e@auda.org.au', '4663 Roth Lane', 'Glendale', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (160, 'Greenholt LLC', '312-331-3501', 'lsinderland4f@bizjournals.com', '1010 Buell Junction', 'Chicago', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (161, 'Kertzmann-Hammes', '785-449-1009', 'dfraczkiewicz4g@jugem.jp', '50460 Jay Junction', 'Topeka', 'Kansas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (162, 'Medhurst-Grady', '716-856-5446', 'celdridge4h@instagram.com', '30 Welch Road', 'Buffalo', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (163, 'Erdman-Nikolaus', '915-475-6871', 'sjessope4i@usgs.gov', '59762 Merry Terrace', 'El Paso', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (164, 'Robel-Wisozk', '540-481-7147', 'fhubeaux4j@xrea.com', '20809 Union Trail', 'Roanoke', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (165, 'Batz, Cormier and Smith', '402-985-8746', 'hmullinder4k@skype.com', '46 Gina Avenue', 'Lincoln', 'Nebraska');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (166, 'Roberts, Walsh and Blick', '320-454-3423', 'egemmill4l@360.cn', '0529 Florence Avenue', 'Saint Cloud', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (167, 'Dicki Group', '602-492-4424', 'caldcorne4m@lulu.com', '398 Crescent Oaks Place', 'Scottsdale', 'Arizona');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (168, 'Ortiz LLC', '512-956-7374', 'cquarmby4n@deviantart.com', '50 Jenifer Trail', 'Austin', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (169, 'Becker Inc', '864-503-1767', 'asouthcomb4o@dmoz.org', '3 Transport Drive', 'Greenville', 'South Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (170, 'Rath-MacGyver', '609-530-0892', 'adioniso4p@constantcontact.com', '5405 Brickson Park Road', 'Trenton', 'New Jersey');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (171, 'Larkin-Dickens', '513-987-1253', 'leagan4q@bbc.co.uk', '4331 Holmberg Road', 'Cincinnati', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (172, 'Gibson Group', '404-443-3833', 'nfavelle4r@a8.net', '9067 Aberg Plaza', 'Atlanta', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (173, 'Littel Inc', '610-634-9832', 'jbook4s@last.fm', '850 Grover Lane', 'Reading', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (174, 'Wiza-West', '812-986-3520', 'rhonywill4t@indiatimes.com', '279 Lindbergh Hill', 'Terre Haute', 'Indiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (175, 'Gusikowski, Yundt and Zulauf', '586-505-0698', 'dnehl4u@behance.net', '34748 Holmberg Drive', 'Detroit', 'Michigan');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (176, 'Ziemann-Stanton', '309-766-8671', 'djoney4v@nymag.com', '9 Luster Hill', 'Carol Stream', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (177, 'Feeney, Smith and Goldner', '612-925-4607', 'dalbery4w@nature.com', '92 Melrose Parkway', 'Minneapolis', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (178, 'Bartell, Abbott and Kling', '216-893-2735', 'achatburn4x@spotify.com', '145 Tennyson Trail', 'Cleveland', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (179, 'McCullough, Mraz and Kunze', '912-999-4118', 'ewadwell4y@patch.com', '1650 Dawn Alley', 'Savannah', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (180, 'Rowe, Wyman and Thiel', '301-329-5785', 'ejenicek4z@sakura.ne.jp', '0904 Rockefeller Terrace', 'Silver Spring', 'Maryland');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (181, 'Konopelski LLC', '919-973-2734', 'jgregr50@huffingtonpost.com', '9 Toban Circle', 'Raleigh', 'North Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (182, 'Hessel and Sons', '202-852-8418', 'aclougher51@cmu.edu', '33683 New Castle Park', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (183, 'Boyer, Reichert and Weimann', '818-585-7176', 'ccolbourne52@springer.com', '67 Chive Plaza', 'Glendale', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (184, 'Witting, Jenkins and Sanford', '267-161-7017', 'hgude53@google.com.au', '662 Eagle Crest Hill', 'Levittown', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (185, 'Bosco and Sons', '843-524-7724', 'ubillo54@hibu.com', '266 1st Avenue', 'Charleston', 'South Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (186, 'Stroman, Rosenbaum and Yost', '419-508-5872', 'qdreye55@npr.org', '9 Carey Parkway', 'Toledo', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (187, 'Powlowski-Harris', '505-815-3385', 'efitzhenry56@wufoo.com', '6173 Elgar Plaza', 'Albuquerque', 'New Mexico');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (188, 'Vandervort Group', '315-888-7538', 'bpostians57@abc.net.au', '6 Springview Park', 'Syracuse', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (189, 'Daugherty-Wiegand', '215-992-3901', 'lhiner58@ucla.edu', '7632 Veith Place', 'Philadelphia', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (190, 'McKenzie, Davis and Senger', '432-789-1207', 'tlynas59@usnews.com', '52505 Lien Terrace', 'Odessa', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (191, 'Sipes Inc', '520-293-7674', 'gdumingo5a@so-net.ne.jp', '66 Weeping Birch Place', 'Phoenix', 'Arizona');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (192, 'Fadel and Sons', '765-189-9474', 'wthresher5b@1und1.de', '39 Ramsey Parkway', 'Lafayette', 'Indiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (193, 'Stracke-Schmeler', '706-494-2454', 'echoules5c@drupal.org', '85 Granby Hill', 'Cumming', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (194, 'Padberg and Sons', '510-858-6555', 'jrichel5d@nature.com', '7 Riverside Crossing', 'Oakland', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (195, 'Casper Group', '763-687-1718', 'agreaterex5e@sciencedaily.com', '328 Carpenter Court', 'Minneapolis', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (196, 'Graham, Hettinger and Batz', '904-663-9162', 'dmarlon5f@desdev.cn', '0780 Crownhardt Trail', 'Jacksonville', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (197, 'Rath, Rippin and Macejkovic', '626-425-9912', 'kwhaymand5g@blog.com', '51743 Kensington Junction', 'Burbank', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (198, 'Champlin Inc', '301-676-2516', 'thadingham5h@skype.com', '53 Straubel Point', 'Hyattsville', 'Maryland');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (199, 'Hilll, Reichel and Russel', '214-211-7467', 'scoweuppe5i@360.cn', '030 Oriole Hill', 'Dallas', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (200, 'Schmidt Inc', '408-497-9891', 'kbolver5j@uol.com.br', '65 Dakota Plaza', 'San Jose', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (201, 'Ritchie, Bauch and Kuhlman', '805-596-5279', 'cgimlet5k@yellowpages.com', '8406 Dennis Street', 'Ventura', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (202, 'Blick-Grady', '754-929-8529', 'abacksal5l@posterous.com', '64 Miller Pass', 'Fort Lauderdale', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (203, 'Brown-Batz', '619-147-1895', 'salmon5m@upenn.edu', '157 Packers Street', 'Chula Vista', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (204, 'Macejkovic Group', '512-134-6630', 'mdank5n@seesaa.net', '14 Orin Way', 'Austin', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (205, 'Koss-Spinka', '859-701-8707', 'spurveys5o@dell.com', '7 Montana Parkway', 'Lexington', 'Kentucky');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (206, 'Gaylord-Lemke', '253-448-1897', 'mcreasy5p@eepurl.com', '4558 Jana Terrace', 'Olympia', 'Washington');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (207, 'Parisian and Sons', '212-537-1333', 'fdenisevich5q@addthis.com', '9666 Luster Court', 'New York City', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (208, 'Hane and Sons', '419-454-1838', 'cbwye5r@sbwire.com', '70 Prentice Alley', 'Mansfield', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (209, 'Abernathy LLC', '719-670-4418', 'llocker5s@nbcnews.com', '50 Lake View Plaza', 'Pueblo', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (210, 'Zieme-Howell', '415-650-4451', 'kfivey5t@lulu.com', '0 Mosinee Terrace', 'San Francisco', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (211, 'Swaniawski LLC', '432-294-7380', 'rsoames5u@ezinearticles.com', '69 Superior Parkway', 'Midland', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (212, 'Monahan, Fay and Nienow', '713-821-7302', 'bkarpf5v@dyndns.org', '4960 Linden Place', 'Houston', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (213, 'Bahringer LLC', '309-224-3684', 'nbills5w@so-net.ne.jp', '2683 Lawn Hill', 'Peoria', 'Illinois');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (214, 'Roob, Wolff and Davis', '515-584-9902', 'mhodges5x@friendfeed.com', '346 Sunbrook Alley', 'Des Moines', 'Iowa');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (215, 'Ward, Franecki and Hessel', '954-215-3534', 'jfebvre5y@gmpg.org', '6 Forest Dale Point', 'Miami', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (216, 'Stracke-Runolfsson', '501-424-0667', 'emorgen5z@yolasite.com', '18109 Oneill Lane', 'North Little Rock', 'Arkansas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (217, 'McGlynn-Gutkowski', '904-347-2076', 'nrookes60@51.la', '565 Esker Crossing', 'Saint Augustine', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (218, 'Bins Group', '907-845-4608', 'mbousquet61@psu.edu', '190 Cottonwood Circle', 'Fairbanks', 'Alaska');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (219, 'Christiansen, Wiegand and Connelly', '626-350-6032', 'estent62@slate.com', '8577 Monument Junction', 'Pasadena', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (220, 'Moen LLC', '419-112-8252', 'hpatershall63@bbc.co.uk', '9 Carberry Junction', 'Toledo', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (221, 'Prohaska-Fahey', '614-399-6867', 'hpharaoh64@tripadvisor.com', '344 Roxbury Avenue', 'Columbus', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (222, 'Mitchell-Luettgen', '423-829-5772', 'mtathacott65@bbc.co.uk', '036 Golf Course Way', 'Johnson City', 'Tennessee');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (223, 'Balistreri Inc', '763-409-8825', 'smccahey66@netlog.com', '628 Miller Trail', 'Monticello', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (224, 'Boyer, Bode and Macejkovic', '727-994-0577', 'wmillard67@etsy.com', '39 Sheridan Terrace', 'Tampa', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (225, 'Schimmel-Towne', '412-206-9730', 'ekingston68@skype.com', '13 Del Sol Junction', 'Pittsburgh', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (226, 'Bashirian, Moore and Hettinger', '210-501-0265', 'agawkes69@last.fm', '40378 Fairview Alley', 'San Antonio', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (227, 'Schaden, Padberg and Orn', '828-162-1845', 'svince6a@bigcartel.com', '78 Esch Place', 'Asheville', 'North Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (228, 'Quigley Group', '757-727-5216', 'wclemendet6b@themeforest.net', '390 Prairieview Hill', 'Suffolk', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (229, 'Gislason, Morar and Franecki', '682-375-1837', 'sormond6c@webmd.com', '12288 Corscot Drive', 'Arlington', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (230, 'Treutel-Schmitt', '801-510-6719', 'bmanneville6d@yale.edu', '0 Carioca Pass', 'Salt Lake City', 'Utah');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (231, 'Ankunding-Rempel', '419-553-1938', 'gledwidge6e@mtv.com', '09 Blackbird Circle', 'Toledo', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (232, 'Hills-Hoppe', '407-461-3827', 'lhatherley6f@cbslocal.com', '307 Reindahl Pass', 'Kissimmee', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (233, 'Schultz, Sauer and Kulas', '704-170-8091', 'jmcshirie6g@shinystat.com', '57320 Menomonie Lane', 'Charlotte', 'North Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (234, 'McDermott Group', '434-220-1490', 'lfagan6h@ucoz.com', '33498 Macpherson Plaza', 'Manassas', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (235, 'Jenkins-Marvin', '916-341-2394', 'cfrosch6i@unblog.fr', '7060 Vernon Parkway', 'Sacramento', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (236, 'McClure, Hartmann and Barrows', '212-638-0815', 'ahaycroft6j@walmart.com', '8 Grover Center', 'New York City', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (237, 'Moen LLC', '913-264-0472', 'gdeancywillis6k@sciencedirect.com', '3 Heath Plaza', 'Shawnee Mission', 'Kansas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (238, 'Zulauf, Herman and Towne', '202-827-8878', 'joilier6l@gov.uk', '6 Lakewood Gardens Alley', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (239, 'Ritchie-Stoltenberg', '212-192-4489', 'bvala6m@icio.us', '5149 Golf Course Lane', 'New York City', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (240, 'Kub, Mertz and Funk', '201-388-4513', 'oabrahm6n@indiegogo.com', '25182 Havey Parkway', 'Paterson', 'New Jersey');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (241, 'Greenfelder-Bechtelar', '334-990-0517', 'dmaccrann6o@people.com.cn', '05 Kingsford Terrace', 'Birmingham', 'Alabama');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (242, 'Mayert, Rosenbaum and Langosh', '251-251-2390', 'mdriuzzi6p@last.fm', '9478 Lindbergh Street', 'Mobile', 'Alabama');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (243, 'Batz-Windler', '410-593-6299', 'tdebill6q@reuters.com', '7 Division Terrace', 'Baltimore', 'Maryland');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (244, 'Mueller Inc', '937-209-2577', 'gfinder6r@tinyurl.com', '24 Pennsylvania Center', 'Dayton', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (245, 'Effertz, Doyle and Hansen', '218-245-5140', 'kdethloff6s@gravatar.com', '417 Dorton Circle', 'Duluth', 'Minnesota');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (246, 'Luettgen Group', '801-969-2924', 'dlishmund6t@usnews.com', '6 Dayton Junction', 'Sandy', 'Utah');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (247, 'Fisher-Olson', '585-491-0679', 'sesterbrook6u@chicagotribune.com', '0 Waywood Alley', 'Rochester', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (248, 'O''Conner, Gorczany and Kuhn', '979-358-6714', 'cyashnov6v@friendfeed.com', '1 Reinke Alley', 'Bryan', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (249, 'Nitzsche Inc', '713-541-8519', 'yslingsby6w@issuu.com', '3457 Holmberg Point', 'Houston', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (250, 'Bernhard and Sons', '303-656-1636', 'amyderscough6x@over-blog.com', '6743 Meadow Ridge Lane', 'Denver', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (251, 'Mante-Welch', '813-976-7399', 'jbeidebeke6y@hostgator.com', '7 Swallow Hill', 'Tampa', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (252, 'Schowalter Inc', '516-237-4516', 'mstorek6z@army.mil', '28 Di Loreto Alley', 'Port Washington', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (253, 'VonRueden-Bednar', '203-718-4059', 'tkarel70@theglobeandmail.com', '5 Summer Ridge Court', 'New Haven', 'Connecticut');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (254, 'Hintz Group', '757-590-5267', 'lcamillo71@freewebs.com', '2 Loomis Hill', 'Chesapeake', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (255, 'Donnelly, Windler and McCullough', '972-785-0642', 'wpawelczyk72@miibeian.gov.cn', '61703 Merry Junction', 'Dallas', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (256, 'Rice Group', '206-405-4369', 'gspondley73@jimdo.com', '3 Hintze Drive', 'Tacoma', 'Washington');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (257, 'Morar-Schmidt', '720-462-8966', 'mjennemann74@istockphoto.com', '15 Farwell Road', 'Denver', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (258, 'Runte-Larkin', '786-169-6800', 'dbouda75@drupal.org', '758 Claremont Lane', 'Miami', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (259, 'Nader Inc', '775-974-0034', 'gforcade76@apple.com', '8 Hudson Pass', 'Carson City', 'Nevada');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (260, 'VonRueden and Sons', '504-355-3643', 'anock77@blogtalkradio.com', '53402 Thackeray Circle', 'Metairie', 'Louisiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (261, 'Bailey, Mohr and D''Amore', '406-424-3407', 'jpersence78@dyndns.org', '48 Moland Alley', 'Missoula', 'Montana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (262, 'Crona, Mante and Kihn', '703-731-7008', 'bpitney79@gizmodo.com', '5788 Roth Court', 'Alexandria', 'Virginia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (263, 'Pollich-Trantow', '410-241-7683', 'ltimny7a@w3.org', '42 Northridge Parkway', 'Ridgely', 'Maryland');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (264, 'Cummings-Gleason', '702-952-8173', 'ctowne7b@state.tx.us', '3 Delladonna Pass', 'Las Vegas', 'Nevada');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (265, 'Pouros-Hessel', '916-426-9006', 'bramard7c@wufoo.com', '4 Hanson Parkway', 'Sacramento', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (266, 'Mayer-Champlin', '864-494-9790', 'lfosdick7d@ezinearticles.com', '76 Rowland Road', 'Spartanburg', 'South Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (267, 'Kuhlman, Little and Stehr', '202-111-0781', 'vperrelli7e@foxnews.com', '0 Magdeline Court', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (268, 'Veum Group', '215-949-4416', 'dcahn7f@4shared.com', '7 Fuller Drive', 'Philadelphia', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (269, 'Kub-Dibbert', '904-192-5709', 'slyburn7g@studiopress.com', '6531 Bluestem Parkway', 'Jacksonville', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (270, 'Macejkovic-Gerlach', '616-457-8133', 'rmatuszak7h@cloudflare.com', '2122 Moose Plaza', 'Grand Rapids', 'Michigan');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (271, 'Towne-Lang', '337-699-2531', 'avannini7i@homestead.com', '1 Victoria Junction', 'Lafayette', 'Louisiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (272, 'Wilderman Group', '919-919-9377', 'slivingstone7j@cmu.edu', '09 Butterfield Lane', 'Raleigh', 'North Carolina');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (273, 'Kreiger Group', '918-491-6611', 'bwilkinson7k@hugedomains.com', '85079 Sundown Alley', 'Tulsa', 'Oklahoma');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (274, 'Brown, Greenholt and Stroman', '260-587-7344', 'ejuckes7l@freewebs.com', '0 Farragut Drive', 'Fort Wayne', 'Indiana');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (275, 'Kunde-Howell', '202-277-0628', 'jeggleston7m@creativecommons.org', '8816 Aberg Avenue', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (276, 'Doyle LLC', '210-310-9981', 'bberrecloth7n@bloglines.com', '67 Sundown Hill', 'San Antonio', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (277, 'Cormier-Braun', '678-277-2819', 'jroskelly7o@berkeley.edu', '76 Dennis Alley', 'Gainesville', 'Georgia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (278, 'Stracke Inc', '205-729-3842', 'sganing7p@youtube.com', '71 Oak Parkway', 'Birmingham', 'Alabama');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (279, 'Larkin, Crona and DuBuque', '214-354-4079', 'sstockport7q@uol.com.br', '1 American Ash Point', 'Garland', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (280, 'Rutherford LLC', '850-213-7823', 'jwartnaby7r@jalbum.net', '041 Onsgard Place', 'Pinellas Park', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (281, 'Weissnat Inc', '502-184-5628', 'mmacdonell7s@scribd.com', '99 Haas Pass', 'Louisville', 'Kentucky');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (282, 'Greenholt, Wolf and Bernhard', '717-586-6452', 'acallery7t@abc.net.au', '18 Jenifer Junction', 'Lancaster', 'Pennsylvania');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (283, 'Shields LLC', '323-210-3126', 'lhincham7u@topsy.com', '260 Ridgeway Terrace', 'Los Angeles', 'California');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (284, 'O''Reilly-Gerlach', '516-848-8320', 'bhastler7v@cnn.com', '81697 Morrow Hill', 'New Hyde Park', 'New York');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (285, 'Jacobson, Wilkinson and Frami', '832-520-4576', 'astealey7w@japanpost.jp', '2610 Manitowish Trail', 'Houston', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (286, 'Kozey LLC', '202-587-6089', 'tizkovici7x@sphinn.com', '68 Mandrake Street', 'Washington', 'District of Columbia');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (287, 'Herman-Cronin', '602-317-9474', 'bdempsey7y@yandex.ru', '5497 Homewood Alley', 'Phoenix', 'Arizona');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (288, 'Rosenbaum LLC', '563-403-3588', 'ashah7z@soup.io', '0123 Lakewood Way', 'Davenport', 'Iowa');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (289, 'Ferry-Toy', '719-928-9427', 'bgetcliffe80@goodreads.com', '78 Spaight Hill', 'Colorado Springs', 'Colorado');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (290, 'Rau and Sons', '702-403-6426', 'rvanichev81@usgs.gov', '1 Service Lane', 'North Las Vegas', 'Nevada');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (291, 'Doyle, Dare and Swift', '850-467-2836', 'fnaisey82@e-recht24.de', '71511 Farmco Junction', 'Tallahassee', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (292, 'Quitzon-Veum', '954-962-2496', 'cliddall83@nationalgeographic.com', '655 Pine View Junction', 'Miami', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (293, 'Barrows-Gusikowski', '937-808-2557', 'bshaxby84@e-recht24.de', '6946 Coolidge Parkway', 'Dayton', 'Ohio');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (294, 'Douglas, Spencer and Stehr', '915-111-3790', 'gvize85@chicagotribune.com', '30 Cardinal Place', 'El Paso', 'Texas');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (295, 'Quigley-Howell', '405-968-7026', 'aegger86@wikimedia.org', '51943 Waywood Avenue', 'Norman', 'Oklahoma');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (296, 'Smitham-Nader', '563-505-6778', 'jbentje87@google.com.hk', '27459 Vera Point', 'Davenport', 'Iowa');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (297, 'Waelchi, Quigley and Bednar', '860-264-7962', 'jelbourne88@gnu.org', '51064 Katie Center', 'Hartford', 'Connecticut');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (298, 'Fritsch-Parisian', '502-794-3675', 'gtatnell89@tumblr.com', '1417 Armistice Pass', 'Louisville', 'Kentucky');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (299, 'Predovic-Bashirian', '813-419-2132', 'kstopforth8a@1und1.de', '5616 Utah Point', 'Tampa', 'Florida');
insert into Vendeur (id, nom, telephone, email, adresse, ville, province) values (300, 'Effertz-Hickle', '361-527-3456', 'crispine8b@google.ru', '16 Monica Crossing', 'Corpus Christi', 'Texas');

select * from Vendeur